### ISSUE TITLE
Manual play not working

### ISSUE THREAD

**Issue by marshallgrimmett** [Kaggle/kaggle-environments#61]
Hi there,

I am having a problem getting the manual play to work.

I get the board to render, but when I click on a column it just says "processing..." and nothing ever happens.

Here's the code:
```
from kaggle_environments import evaluate, make, utils
env = make("connectx", debug=True)
env.play([None, "negamax"], width=800, height=600)
```

I have tried using "random" instead of "negamax" and I have also tried switching to second player, but nothing works.

Here are the versions I am using.
```
Python                        3.7.4
kaggle-environments           1.0.13
jupyterlab                    2.1.4
ipython                       7.13.0
```

Thank you,
Marshall

**Comment by harrisse** [comment]
Thanks for the report, we'll take a look!

**Comment by richard-hajek** [comment]
I second this. Reproduction is very easy. This docker-compose.yml:

```
version: '2.0'
services:
  jupyter:
    image: gcr.io/kaggle-images/python
    command: jupyter lab --allow-root
    volumes:
    - .:/working
    working_dir: /working
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
        HOME: '/working'
```

Browser: Firefox 80.0.1 (same result on Google Chrome 85.0.4183.102 (Official Build) (64-bit) )

Result:

![image](https://user-images.githubusercontent.com/29554823/93650702-8f120e00-fa0f-11ea-84a1-d635a897ee37.png)

And this just hangs like that seemingly forever

**Comment by SiggyF** [comment]
I have the same issue. I see the following error in the console log:
```
Error: IPython Unavailable: TypeError: Cannot read property 'notebook' of undefined
    at about:srcdoc:1171
    at new Promise (<anonymous>)
    at App.contextRef.current.execute (about:srcdoc:1158)
    at App.contextRef.current.act (about:srcdoc:1179)
    at HTMLCanvasElement.<anonymous> (about:srcdoc:332)
(anonymous) @ about:srcdoc:1199
Promise.catch (async)
App.contextRef.current.act @ about:srcdoc:1199
(anonymous) @ about:srcdoc:332
```

**Comment by bovard** [comment]
I've gone a number of reports on this on the kaggle forums as well. I will try to prioritize to take a look at this.

**Comment by SiggyF** [comment]
The current player [code](https://github.com/Kaggle/kaggle-environments/blob/ec90612db9c035af91b26f029a862e6b1a185ff6/kaggle_environments/static/player.html#L620) seems to depend on the `ipython` javascript API. I inspected the kaggle javascript environment using a javascript cell:
```
%%javascript
// Show python related variables
console.log('vars', Object.keys(window).filter(x => x.toLowerCase().match(/py/)))
```

This shows that the current kaggle version is using the `JupyterLab` environment. I couldn't find an easy way (other then by writing a jupyter lab extension to recreate the similar functionality. See also the open issue [here](https://github.com/jupyterlab/jupyterlab/issues/5660) .

**Comment by jonahw23** [comment]
I'm having this issue as well, I've tried running a Jupyter notebook locally as well as using Google Colab and the Kaggle Notebooks, but I get the same "Processing" message no matter the enviroment. Any workarounds?

**Comment by kafkasl** [comment]
> I'm having this issue as well, I've tried running a Jupyter notebook locally as well as using Google Colab and the Kaggle Notebooks, but I get the same "Processing" message no matter the enviroment. Any workarounds?

hey it didn't work for me using Jupyter Lab but it did work using normal notebooks. 
In the terminal, instead of running`jupyter lab`, run `jupyter notebook`

**Comment by eeoooue** [comment]
Just to add some more context, this was still broken for me when running 0.1.6 today, locally on Windows with Docker Desktop:
- I tried pinning the kaggle-environments version to 0.1.6 as per [this bug thread](https://www.kaggle.com/discussions/product-feedback/702435)
- the IPython display hangs on Processing... when attempting to play manually

<img width="525" height="669" alt="Image" src="https://github.com/user-attachments/assets/08db86ff-52cf-45cf-8e81-f4fb80c41e0c" />

### Docker Compose

I used a windows adjusted version of the compose shared by @richard-hajek

```yaml
version: '2.0'
services:
  jupyter:
    image: gcr.io/kaggle-images/python
    command: jupyter lab --allow-root --ip=0.0.0.0 --no-browser
    volumes:
    - .:/working
    working_dir: /working
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    environment:
        HOME: '/working'
```

I launch the compose using plainly:

```
docker compose up --build --detach
```


### Kaggle Environments Snippet

I created a notebook in the served jupyter lab instance with the below code:

```python
!pip install 'kaggle-environments==0.1.6'

from kaggle_environments import make

env = make("connectx")
env.play([None, "random"])
```

**Comment by eeoooue** [comment]
As suggested by @kafkasl, I tried using jupyter notebook instead of jupyter lab and was able to use the IPython display as intended. Again, I pinned my kaggle-environments version to 0.1.6.

<img width="481" height="453" alt="Image" src="https://github.com/user-attachments/assets/2b11acbf-069d-4cfa-8ba8-7e159fa7df09" />

### Docker Compose

I changed the Docker compose to use jupyter **notebook instead of lab**

```yaml
version: '2.0'
services:
  jupyter:
    image: gcr.io/kaggle-images/python
    command: jupyter notebook --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password=''
    volumes:
    - .:/working
    working_dir: /working
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    environment:
        HOME: '/working'
```

```
docker compose up --build --detach
```

### Kaggle Environments Snippet

I used the same code in the notebook as before:

```python
!pip install 'kaggle-environments==0.1.6'

from kaggle_environments import make

env = make("connectx")
env.play([None, "random"])
```

#### Recommendation

For anyone else trying to get kaggle-environments visualizations for connectx working in a self-hosted Docker setup:
- use jupyter notebook instead of lab (thanks @kafkasl)
- pin kaggle-environments to v0.1.6 (thanks [lucyhe2](https://www.kaggle.com/discussions/product-feedback/702435))
